// clues.js
const cluesDB = {
  "David & Goliath": {
    "1": [
      { location: "Canteen", clue: "In times of battle, even a young shepherd must gather strength and courage. Begin where meals fuel the body and prepare yourself for the fight ahead." },
      { location: "Bicycle Shed CSE", clue: "Like a steadfast warrior mounts a faithful steed, find your path among the resting bikes awaiting their riders." },
      { location: "Emmanuel Auditorium", clue: "Faith is your shield; here, in a place named ‘God with us,’ strengthen your spirit for the challenge." },
      { location: "Agri Lab - 4 Trees Area", clue: "Five smooth stones were chosen beside peaceful waters and sheltering trees. Find refuge beneath four mighty guardians of nature." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Step through gates named for healing and divine power, advancing in both faith and strength." },
      { location: "Mechanical Trees", clue: "Like giants among men, these metal trees stand tall. Seek here for wisdom to defeat giants." },
      { location: "Library", clue: "Knowledge armed David more than sword or shield. Find your next clue among the shelves of wisdom." },
      { location: "CTC 2 Placement Training", clue: "Preparation is key; even champions sharpen their skills before battle in places like this." },
      { location: "Cake World Trees", clue: "Nature’s sweetness and shade provide rest for those on perilous journeys. Find the quiet refuge beneath these trees." },
      { location: "ECE Vending Machine", clue: "Small provisions can save the day—seek the place where coins turn into nourishing treasures." },
      { location: "Aeroplane", clue: "Faith lifted David higher than fear, soaring beyond giants. Find this symbol of flight and courage." },
      { location: "Main Building Trees", clue: "Beneath these trees lies the victory of the fearless. Claim your prize here where the journey ends." }
    ],
    "2": [
      { location: "Bicycle Shed CSE", clue: "Like a reliable steed, these bikes wait for their riders to begin the journey of courage. Mount your mission here." },
      { location: "Emmanuel Auditorium", clue: "With God as your guide, faith strengthens you here in this house where hope dwells." },
      { location: "Agri Lab - 4 Trees Area", clue: "David chose five smooth stones by peaceful waters and shade—rest beneath these trees to prepare." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Step through sacred gates named for healing and God's might, moving closer to victory." },
      { location: "Mechanical Trees", clue: "Steel giants tower here. Find strength and courage in this metallic forest." },
      { location: "Library", clue: "The shepherd boy’s wisdom was gathered here among the books. Find your next clue in these halls." },
      { location: "CTC 2 Placement Training", clue: "Where champions sharpen their skills, prepare for your face-off with the giant." },
      { location: "Cake World Trees", clue: "Nature’s sweetness and shade offer calm before the storm. Find refuge beneath these branches." },
      { location: "ECE Vending Machine", clue: "Small but mighty, provisions here sustain you. Seek nourishment from this humble machine." },
      { location: "Aeroplane", clue: "Lift your courage high as wings spread wide. Find this flying giant and fly above fear." },
      { location: "Main Building Trees", clue: "Victory lies beneath these towering trees. Rest here and celebrate your triumph." },
      { location: "Canteen", clue: "Return to nourish your body and soul where the journey began." }
    ],
    "3": [
      { location: "Emmanuel Auditorium", clue: "Start where God’s presence is felt and faith is born strong. Begin your journey in hope and courage." },
      { location: "Agri Lab - 4 Trees Area", clue: "Five smooth stones were chosen beside peaceful waters and under sheltering trees. Find rest here." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Pass through these sacred gates named for healing and divine might to move closer to victory." },
      { location: "Mechanical Trees", clue: "Among towering steel giants, find your strength and wisdom to face the challenge." },
      { location: "Library", clue: "The shepherd’s wisdom came here; seek knowledge for your battle." },
      { location: "CTC 2 Placement Training", clue: "Prepare your mind and spirit where champions ready themselves." },
      { location: "Cake World Trees", clue: "Nature’s sweetness offers refuge. Rest and prepare your heart beneath the trees." },
      { location: "ECE Vending Machine", clue: "Small offerings here can save the day. Find these hidden treasures." },
      { location: "Aeroplane", clue: "Lift your spirit above fear, just like wings cutting the sky. Find the soaring giant." },
      { location: "Main Building Trees", clue: "Here beneath mighty trees, the battle ends and victory is claimed." },
      { location: "Canteen", clue: "Gather strength again here before the final steps." },
      { location: "Bicycle Shed CSE", clue: "Mount your steed and ride to the finish, your courage strong as ever." }
    ],
    "4": [
      { location: "Agri Lab - 4 Trees Area", clue: "Begin your courageous journey under these steadfast trees, where David chose his stones for battle." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Pass through gates of healing and divine strength to continue your quest." },
      { location: "Mechanical Trees", clue: "Steel giants stand tall here—find wisdom and courage among them." },
      { location: "Library", clue: "David’s knowledge was the sharpest weapon—seek his wisdom here." },
      { location: "CTC 2 Placement Training", clue: "Prepare for battle here where champions train their minds and hearts." },
      { location: "Cake World Trees", clue: "Rest beneath sweet trees, finding peace before your final confrontation." },
      { location: "ECE Vending Machine", clue: "Sustenance from small offerings can make great victories possible—find your provisions here." },
      { location: "Aeroplane", clue: "Soar above fear and doubt like wings unfolding. The flying giant awaits." },
      { location: "Main Building Trees", clue: "Rest beneath these trees where victory's calm descends and courage is rewarded." },
      { location: "Canteen", clue: "Return to nourish and gather strength for the final steps." },
      { location: "Bicycle Shed CSE", clue: "Mount your steadfast ride for the last stretch of the journey." },
      { location: "Emmanuel Auditorium", clue: "End where God’s presence strengthens the soul, completing your journey of faith." }
    ],
    "5": [
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Begin your journey through these gates of healing and might, stepping into the path of courage and faith." },
      { location: "Mechanical Trees", clue: "Among the steel giants, gather strength for the battle ahead." },
      { location: "Library", clue: "Seek wisdom here, where David’s courage took root in stories and knowledge." },
      { location: "CTC 2 Placement Training", clue: "Prepare your mind and spirit to face the giant’s challenge." },
      { location: "Cake World Trees", clue: "Rest beneath these sweet trees, gathering peace and courage." },
      { location: "ECE Vending Machine", clue: "Small treasures here will sustain you on the path forward—find them wisely." },
      { location: "Aeroplane", clue: "Lift your spirit like wings above fear, finding freedom and hope." },
      { location: "Main Building Trees", clue: "Victory rests beneath these mighty trees; claim your prize here." },
      { location: "Canteen", clue: "Gather your final strength here where the journey began." },
      { location: "Bicycle Shed CSE", clue: "Equip your steed for the last ride toward success." },
      { location: "Emmanuel Auditorium", clue: "Feel God’s presence strengthen your soul in this sacred space." },
      { location: "Agri Lab - 4 Trees Area", clue: "Complete your journey beneath the trees where the stones were chosen and faith was made strong." }
    ]
  },

  "Jonah and the Whale": {
    "1": [
      { location: "Aeroplane", clue: "Like Jonah who fled by ship, start your journey beneath mighty wings ready to set flight and face destiny." },
      { location: "Main Building Trees", clue: "Rest beneath these trees where trials are faced in silence and faith is renewed." },
      { location: "Canteen", clue: "Prepare yourself with nourishment, for the journey to obedience can be taxing to mind and body." },
      { location: "Mechanical Trees", clue: "Amidst these steel giants find strength to face the darkness within, much like Jonah in the deep." },
      { location: "Library", clue: "Seek wisdom and stories of mercy in the quiet pages, a beacon for those who stray." },
      { location: "Cake World Trees", clue: "Find the sweet refuge under these trees, just as Jonah found solace in the storm." },
      { location: "Bicycle Shed CSE", clue: "Where silent steeds rest, find resolve to move onward on your mission." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Pass through gateways of healing and divine promise, stepping closer to redemption." },
      { location: "Emmanuel Auditorium", clue: "Feel God’s presence guide you as it did Jonah, bringing faith and hope anew." },
      { location: "Agri Lab - 4 Trees Area", clue: "Rest beneath these tall trees, finding patience and quiet strength for the path ahead." },
      { location: "ECE Vending Machine", clue: "Small provisions sustain great missions—find your next support here." },
      { location: "CTC 2 Placement Training", clue: "Prepare your mind and heart for the choices ahead, just as Jonah faced his." }
    ],
    "2": [
      { location: "Canteen", clue: "Jonah first fled the call, but the journey begins here where strength is gathered for the tasks ahead." },
      { location: "Mechanical Trees", clue: "Among these metallic giants find courage to face your fears and the unknown depths." },
      { location: "Library", clue: "Seek stories of mercy and guidance that illuminate the darkest waters." },
      { location: "Cake World Trees", clue: "Find peace beneath sweet-scented branches, a reminder of second chances." },
      { location: "Bicycle Shed CSE", clue: "Here, steady your resolve; silent steeds ready to carry you forward." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Step through gates dedicated to healing and divine power as your spirit renews." },
      { location: "Emmanuel Auditorium", clue: "Called by faith and divine presence, strengthen yourself here." },
      { location: "Agri Lab - 4 Trees Area", clue: "Breathe and rest in the natural shade, collecting patience for the storm inside." },
      { location: "ECE Vending Machine", clue: "Small provisions fuel big journeys—discover your sustenance here." },
      { location: "CTC 2 Placement Training", clue: "Sharpen your mind and spirit for the responsibilities ahead." },
      { location: "Aeroplane", clue: "Like soaring wings breaking storms, find the symbol of hope and deliverance ahead." },
      { location: "Main Building Trees", clue: "At journey’s end, rest beneath these protective trees and reflect on mercy gained." }
    ],
    "3": [
      { location: "Library", clue: "Jonah’s story of mercy begins here in the pages of ancient wisdom and faith." },
      { location: "Cake World Trees", clue: "Sheltered beneath sweet trees, patience and peace grow in even the hardest places." },
      { location: "Bicycle Shed CSE", clue: "Strengthen your resolve here where silent steeds await your journey forward." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Cross through gates of healing and immense power, your spirit ready for new beginnings." },
      { location: "Emmanuel Auditorium", clue: "God’s presence strengthens your heart for what is to come." },
      { location: "Agri Lab - 4 Trees Area", clue: "Gather strength beneath these enduring trees, steady and patient as your journey continues." },
      { location: "ECE Vending Machine", clue: "Find sustenance in small offerings that fuel great change on your path." },
      { location: "CTC 2 Placement Training", clue: "Prepare your mind and courage as Jonah prepared to obey." },
      { location: "Aeroplane", clue: "Rise above the tempest with wings of hope found within steel giants." },
      { location: "Main Building Trees", clue: "Journey ends under protective trees where mercy and faith flourish." },
      { location: "Canteen", clue: "Nourish your body and soul with food and fellowship before the next leg." },
      { location: "Mechanical Trees", clue: "Among towering mechanical trees, prepare for the path to obedience and grace." }
    ],
    "4": [
      { location: "Agri Lab - 4 Trees Area", clue: "Begin beneath these four mighty trees where peace calms the storm within." },
      { location: "ECE Vending Machine", clue: "Small provisions sustain your journey just as mercy sustains the soul." },
      { location: "CTC 2 Placement Training", clue: "Sharpen your resolve and prepare your heart for obedience’s trials." },
      { location: "Aeroplane", clue: "Look to the sky; bold wings part storms and carry hope higher." },
      { location: "Main Building Trees", clue: "Rest beneath these ancient trees where faith carries the weary." },
      { location: "Canteen", clue: "Gain strength in fellowship and nourishment for the trials ahead." },
      { location: "Mechanical Trees", clue: "Amongst steel giants, find courage to face the darkest moments." },
      { location: "Library", clue: "Seek knowledge and guidance in stories of mercy and redemption." },
      { location: "Cake World Trees", clue: "Nature’s sweet refuge offers peace before the next step." },
      { location: "Bicycle Shed CSE", clue: "Silent steeds wait to carry you forward with steady purpose." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Cross gates named for healing and divine strength as you advance." },
      { location: "Emmanuel Auditorium", clue: "God’s presence guides your final steps toward obedience and hope." }
    ],
    "5": [
      { location: "CTC 2 Placement Training", clue: "Begin here where minds sharpen and courage is fortified to face difficult choices." },
      { location: "Aeroplane", clue: "Lift your spirit above the storm, symbolized by these soaring wings." },
      { location: "Main Building Trees", clue: "Find protection beneath towering trees, sheltering the faithful." },
      { location: "Canteen", clue: "Gather nourishment to strengthen both body and spirit for your quest." },
      { location: "Mechanical Trees", clue: "Amongst towering steel giants, build your resolve against life's tempests." },
      { location: "Library", clue: "Discover stories of mercy and grace lighting the way to redemption." },
      { location: "Cake World Trees", clue: "Rest among sweet-scented boughs, drawing peace from gentle nature." },
      { location: "Bicycle Shed CSE", clue: "Ready your silent steeds, as your journey continues forward." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Pass through gates of healing and divine power, stepping closer to mercy." },
      { location: "Emmanuel Auditorium", clue: "God with us—the presence that strengthens those who follow His call." },
      { location: "Agri Lab - 4 Trees Area", clue: "Shelter beneath four mighty trees as you prepare for your next steps." },
      { location: "ECE Vending Machine", clue: "Small tokens here will fuel your final movement toward mercy and obedience." }
    ]
  },

  "Moses and the Red Sea": {
    "1": [
      { location: "Canteen", clue: "Every journey toward freedom begins with sustaining your body and spirit. Gather here among the scent of food and fellowship, fortifying yourself for the great mission ahead." },
      { location: "Bicycle Shed CSE", clue: "Like Moses mounting his path to lead his people, find the resting place of silent steeds ready for the ride into destiny." },
      { location: "Emmanuel Auditorium", clue: "‘God with us’ guides every step; here faith strengthens the heart for the challenges ahead." },
      { location: "Agri Lab - 4 Trees Area", clue: "Beneath these four towering trees, find shelter and renewed strength, reflecting the refuge found in the wilderness." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Step beyond gates named for healing and divine strength; crossing here brings you closer to freedom." },
      { location: "Mechanical Trees", clue: "Among these towering steel giants, find wisdom and courage as Moses found guidance in the unknown." },
      { location: "Library", clue: "Seek refuge in the stories of faith, perseverance, and deliverance kept within these walls." },
      { location: "CTC 2 Placement Training", clue: "Where leaders train in strength and skill, prepare your mind and spirit for the trials ahead." },
      { location: "Cake World Trees", clue: "Find sanctuary amid these sweet-scented trees, a place of calm amid your journey’s wilderness." },
      { location: "ECE Vending Machine", clue: "Small provisions here sustain great voyages—discover the nourishment you need to proceed." },
      { location: "Aeroplane", clue: "Like wings parting mighty seas, this soaring giant symbolizes the freedom you seek—look up and ascend." },
      { location: "Main Building Trees", clue: "Beneath these grand trees flow the footsteps of many who have journeyed toward freedom—rest and claim your victory here." }
    ],
    "2": [
      { location: "Bicycle Shed CSE", clue: "Silent steeds stand ready here, just as Moses’ path began with steady steps forward. Mount your resolve and begin your quest." },
      { location: "Emmanuel Auditorium", clue: "Where God’s presence comforts and inspires, find your spirit uplifted for the challenges ahead." },
      { location: "Agri Lab - 4 Trees Area", clue: "Find shelter beneath these four mighty trees where strength and peace reside in nature’s embrace." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Step through gates bearing sacred names of healing and mighty power, unlocking new paths forward." },
      { location: "Mechanical Trees", clue: "Amidst towering steel giants, draw courage and insight for your journey’s next trial." },
      { location: "Library", clue: "The ancient stories held here illuminate the path and fortify weary hearts." },
      { location: "CTC 2 Placement Training", clue: "This is the place where great leaders ready their minds for challenges yet to come." },
      { location: "Cake World Trees", clue: "Rest among sweet-scented trees as the desert wanderers found respite beneath leaf and branch." },
      { location: "ECE Vending Machine", clue: "Small offerings to sustain great missions await here; find your provisions." },
      { location: "Aeroplane", clue: "Soar like wings over parted seas—the giant metal bird symbolizes your deliverance." },
      { location: "Main Building Trees", clue: "Walk beneath these towering trees where freedom’s footsteps shape the earth—rest now in victory." },
      { location: "Canteen", clue: "Return now to nourish your body and spirit as the final step of your journey." }
    ],
    "3": [
      { location: "Emmanuel Auditorium", clue: "Begin where God’s promise ‘with us’ fills hearts and arms them with strength to lead." },
      { location: "Agri Lab - 4 Trees Area", clue: "Beneath these towering sentinels, find peace like that which sustained the Israelites wandering the desert." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Cross through gates of healing and divine might, stepping boldly into your freedom." },
      { location: "Mechanical Trees", clue: "Among steel giants, find courage and resolve reminiscent of the journey through parted waters." },
      { location: "Library", clue: "In these halls of wisdom, find the ancient stories that give power to those who seek freedom." },
      { location: "CTC 2 Placement Training", clue: "Prepare your mind, body, and spirit where leaders ready themselves for great missions." },
      { location: "Cake World Trees", clue: "The sweet trees offer solace and calm on the path through the wilderness." },
      { location: "ECE Vending Machine", clue: "Small tokens here provide strength as the manna sustained those on a perilous journey." },
      { location: "Aeroplane", clue: "Lift your spirit above waves of doubt, represented by the soaring wings above." },
      { location: "Main Building Trees", clue: "Rest beneath the mighty trees where many have walked toward hope and liberty." },
      { location: "Canteen", clue: "Gather nourishment here to face your final step with vigor and faith." },
      { location: "Bicycle Shed CSE", clue: "Mount your silent steed for the last leg of your journey to freedom." }
    ],
    "4": [
      { location: "Agri Lab - 4 Trees Area", clue: "Start beneath these steadfast trees that symbolize shelter and renewal during long wilderness journeys." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Pass through gates named for healing and God’s mighty name; your path to freedom continues here." },
      { location: "Mechanical Trees", clue: "Steel giants tower here; find wisdom and courage in their shadow for the journey’s next challenge." },
      { location: "Library", clue: "Seek strength in stories told here—tales of faith and deliverance that inspire endurance." },
      { location: "CTC 2 Placement Training", clue: "Prepare where leadership is forged through discipline and determination." },
      { location: "Cake World Trees", clue: "Sweet shade and fragrant calm await you; rest here to restore balance and hope." },
      { location: "ECE Vending Machine", clue: "Small offerings here can sustain big dreams; find your provisions for the path ahead." },
      { location: "Aeroplane", clue: "Like wings that part the sea, this giant metal bird symbolizes soaring toward freedom." },
      { location: "Main Building Trees", clue: "Walk beneath these great trees, where hope flourishes and journeys conclude." },
      { location: "Canteen", clue: "Gather your final strength among friends and food before completing the quest." },
      { location: "Bicycle Shed CSE", clue: "Steeds ready, mount for the final ride toward success." },
      { location: "Emmanuel Auditorium", clue: "Rest in the presence of God, where faith is your ultimate strength and victory is yours." }
    ],
    "5": [
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Begin your journey through sacred gates named for healing and divine power, symbolizing passage from bondage to freedom." },
      { location: "Mechanical Trees", clue: "Among the towering steel giants, summon the courage to face the unknown." },
      { location: "Library", clue: "Turn to the stories ancient and wise to find strength for your continued journey." },
      { location: "CTC 2 Placement Training", clue: "Sharpen your mind and heart where leaders prepare to lead with purpose and courage." },
      { location: "Cake World Trees", clue: "Find refuge and peace amid the sweet-scented shade, mirroring the respite in the journey through the wilderness." },
      { location: "ECE Vending Machine", clue: "Small provisions will sustain you here—holding onto hope like the manna of old." },
      { location: "Aeroplane", clue: "Wings spread wide, soaring over parted seas—a symbol of faith and freedom." },
      { location: "Main Building Trees", clue: "Rest beneath towering trees where footsteps of hope and victory are worn into the earth." },
      { location: "Canteen", clue: "Renew strength and fellowship here, readying for the journey’s last steps." },
      { location: "Bicycle Shed CSE", clue: "Mount your silent steed and prepare for the final sprint toward freedom." },
      { location: "Emmanuel Auditorium", clue: "Feel God’s enduring presence strengthen your soul for victory." },
      { location: "Agri Lab - 4 Trees Area", clue: "End your journey under these mighty trees where resilience and faith brought victory over adversity." }
    ]
  },

  "Noah's Ark": {
    "1": [
      { location: "Library", clue: "Begin where ancient words tell of obedience and salvation. Within these pages, prepare your heart for the coming journey." },
      { location: "Cake World Trees", clue: "Find solace beneath sweet-scented trees, reflecting the pairs of creatures sheltered in Noah’s ark." },
      { location: "CTC 2 Placement Training", clue: "Great tasks require preparation. Sharpen your mind here to build strength for the ark’s voyage." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Step through gates named for healing and God’s power, moving toward sanctuary." },
      { location: "Mechanical Trees", clue: "Among steel giants, find resolve and courage to face the flood ahead." },
      { location: "Agri Lab - 4 Trees Area", clue: "Beneath four stalwart trees, find shelter and reflection as Noah did in the storm’s eye." },
      { location: "Aeroplane", clue: "Look up to the giant wings that symbolize hope soaring over turbulent waters." },
      { location: "Bicycle Shed CSE", clue: "Steeds lie rest here, steady and ready to carry those who walk in obedience." },
      { location: "Emmanuel Auditorium", clue: "God’s presence reminds you of the covenant—strength to endure the flood." },
      { location: "ECE Vending Machine", clue: "Small offerings sustain great voyages—find your provisions here." },
      { location: "Canteen", clue: "Refuel with food and fellowship, gathering strength for what lies ahead." },
      { location: "Main Building Trees", clue: "Walk beneath these mighty trees where new beginnings take root after the storm." }
    ],
    "2": [
      { location: "Cake World Trees", clue: "Begin beneath sweet-scented boughs, a reminder of the pairs sheltered in Noah’s ark from the flood." },
      { location: "CTC 2 Placement Training", clue: "Preparation is essential when building a refuge. Sharpen your mind here for the coming trials." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Pass through stately gates named for healing and God’s strength—symbols of hope." },
      { location: "Mechanical Trees", clue: "Among towering steel giants, find resilience for the journey’s stormy seas." },
      { location: "Agri Lab - 4 Trees Area", clue: "This small forest offers shelter and calm, mirroring Noah’s safe haven among nature." },
      { location: "Aeroplane", clue: "The mighty wings above symbolize hope rising beyond floodwaters, a beacon of salvation." },
      { location: "Bicycle Shed CSE", clue: "Silent steeds rest here waiting to carry you forward with steady purpose." },
      { location: "Emmanuel Auditorium", clue: "Feel God’s protective presence around you like the ark's shelter in the storm." },
      { location: "ECE Vending Machine", clue: "Small provisions await to sustain your voyage toward safety." },
      { location: "Canteen", clue: "Gather strength here with nourishing meals and warm company." },
      { location: "Main Building Trees", clue: "Under great trees, new life begins—walk this path toward renewal." },
      { location: "Library", clue: "End your journey where stories of faith, obedience, and salvation reside, inspiring all who seek refuge." }
    ],
    "3": [
      { location: "CTC 2 Placement Training", clue: "Preparation is the foundation of great tasks. Begin here where leaders ready their minds and hearts." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Step through these gates of healing and divine power, crossing into safety’s embrace." },
      { location: "Mechanical Trees", clue: "Among the steel giants, steel your courage for the trials ahead." },
      { location: "Agri Lab - 4 Trees Area", clue: "Under these steadfast trees, find calm and renewal amidst the storm." },
      { location: "Aeroplane", clue: "Look to the skies where wings spread wide symbolize deliverance and hope." },
      { location: "Bicycle Shed CSE", clue: "Silent companions rest here, ready to carry you forward steadily." },
      { location: "Emmanuel Auditorium", clue: "Here God’s presence offers protection and hope for the faithful." },
      { location: "ECE Vending Machine", clue: "Small tokens nourish great missions; find your provisions here." },
      { location: "Canteen", clue: "Gather strength and warmth among fellowship and food." },
      { location: "Main Building Trees", clue: "Walk beneath mighty trees where new beginnings emerge after the flood." },
      { location: "Library", clue: "Seek wisdom and courage among ancient stories, the heart of your journey." },
      { location: "Cake World Trees", clue: "End where sweet trees offer peace, sheltering the faithful like the ark itself." }
    ],
    "4": [
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Begin at gates that symbolize healing and divine strength—a sacred threshold to salvation." },
      { location: "Mechanical Trees", clue: "Among steel giants, summon strength to weather the coming storm." },
      { location: "Library", clue: "Ancient tales within these walls inspire obedience and faith through great trials." },
      { location: "CTC 2 Placement Training", clue: "Sharpen your focus and fortify your mind here for great works ahead." },
      { location: "Cake World Trees", clue: "Sweet shade and calm welcome those journeying toward new beginnings." },
      { location: "Agri Lab - 4 Trees Area", clue: "Find solace beneath these tall trees, the ark of nature’s protection." },
      { location: "Aeroplane", clue: "Soaring wings above remind us that hope rises above the flood." },
      { location: "Bicycle Shed CSE", clue: "Steeds rest here, ready to carry you forward with steady assurance." },
      { location: "Emmanuel Auditorium", clue: "God’s presence here reaffirms faith and protection." },
      { location: "ECE Vending Machine", clue: "Small gifts here sustain your progress as manna sustained the faithful." },
      { location: "Canteen", clue: "Renew yourself where nourishment and fellowship abound." },
      { location: "Main Building Trees", clue: "Complete your journey beneath majestic trees symbolizing new life after hardship." }
    ],
    "5": [
      { location: "Aeroplane", clue: "Begin your ark’s journey beneath mighty wings that soar, symbols of deliverance over troubled waters." },
      { location: "Main Building Trees", clue: "Walk under these mighty trees, witnesses of many new beginnings after the storm." },
      { location: "Canteen", clue: "Gather strength here, fueling your body and spirit for the voyage ahead." },
      { location: "Mechanical Trees", clue: "In this steel forest, steel your resolve to face the coming flood." },
      { location: "Library", clue: "Seek refuge in wisdom’s pages, ancient tales guiding the faithful through trials." },
      { location: "Cake World Trees", clue: "Rest beneath sweet trees, a small haven like the ark in a world of storms." },
      { location: "CTC 2 Placement Training", clue: "Prepare your mind and heart here—the builder’s workshop for steadfast leaders." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Step past gates named for healing and power, moving closer to salvation." },
      { location: "Agri Lab - 4 Trees Area", clue: "Find shelter beneath four mighty sentinels as Noah did during the flood’s fury." },
      { location: "Bicycle Shed CSE", clue: "Silent steeds rest, ready to steady your journey forward." },
      { location: "Emmanuel Auditorium", clue: "God’s presence shelters and sustains those who trust in His covenant." },
      { location: "ECE Vending Machine", clue: "Small offerings fuel great missions—find your sustenance here before completing your journey." }
    ]
  },

  "Daniel in the Lion's Den": {
    "1": [
      { location: "Canteen", clue: "Even the bravest need strength. Begin your journey where nourishment fuels the body and courage begins to grow." },
      { location: "Bicycle Shed CSE", clue: "Like Daniel on his steadfast path, find the resting steeds ready to carry you forward with resolve." },
      { location: "Emmanuel Auditorium", clue: "Where God is with us, faith stands firm even in the face of danger. Gather your spirit here." },
      { location: "Agri Lab - 4 Trees Area", clue: "Under the protection of these four mighty trees, find calm before entering the den of challenge." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Pass through gates named for healing and divine power, stepping closer to courage rewarded." },
      { location: "Mechanical Trees", clue: "Among towering steel giants, gather the strength to face your lions fearlessly." },
      { location: "Library", clue: "Seek wisdom and courage in the stories written here—they will light your way in the darkness." },
      { location: "CTC 2 Placement Training", clue: "Prepare your mind to face trials with bravery, as Daniel prepared to stand for his faith." },
      { location: "Cake World Trees", clue: "Rest beneath these sweet-scented trees, reflecting on hope in the midst of challenge." },
      { location: "ECE Vending Machine", clue: "Small provisions fortify the spirit; find your next source of strength here." },
      { location: "Aeroplane", clue: "Like soaring wings that rise above danger, find the symbol of freedom and faith here." },
      { location: "Main Building Trees", clue: "Beneath these towering trees, courage prevails. Claim your victory at this journey’s end." }
    ],
    "2": [
      { location: "Bicycle Shed CSE", clue: "Mount your silent steeds and steady your heart; your journey of courage begins here." },
      { location: "Emmanuel Auditorium", clue: "In this place of God’s presence, find your faith renewed and strengthened." },
      { location: "Agri Lab - 4 Trees Area", clue: "Find refuge beneath these four mighty trees, a sanctuary from fear and doubt." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Step through healing gates imbued with divine power, moving bravely forward." },
      { location: "Mechanical Trees", clue: "Stand strong among these great metal giants; courage grows in the shadows of strength." },
      { location: "Library", clue: "Within these walls lies wisdom to light your path through the darkest of fears." },
      { location: "CTC 2 Placement Training", clue: "Prepare your mind and spirit here; bravery is born in preparation." },
      { location: "Cake World Trees", clue: "Sweet trees offer calm and hope, a gentle respite from life’s dangers." },
      { location: "ECE Vending Machine", clue: "Small but vital provisions sustain your courage—find these hidden treasures." },
      { location: "Aeroplane", clue: "Rising wings above remind us to soar over fears and doubts with faith." },
      { location: "Main Building Trees", clue: "Walk beneath mighty trees where courage has triumphed time and again." },
      { location: "Canteen", clue: "Return to nourishment and fellowship as you complete your courageous journey." }
    ],
    "3": [
      { location: "Emmanuel Auditorium", clue: "Begin where God’s presence assures faith and courage in the face of trials." },
      { location: "Agri Lab - 4 Trees Area", clue: "Shelter beneath these steadfast trees, a reminder that calm courage strengthens the heart." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Cross gates named for healing and divine might, stepping closer to victory through faith." },
      { location: "Mechanical Trees", clue: "Among steel giants, find your strength to face your fears boldly." },
      { location: "Library", clue: "Seek knowledge and strength among these quiet halls that tell stories of faith and triumph." },
      { location: "CTC 2 Placement Training", clue: "Sharpen your resolve here; preparation births courage." },
      { location: "Cake World Trees", clue: "Rest beneath sweet trees where hope flourishes even in peril." },
      { location: "ECE Vending Machine", clue: "Provisions small and essential await here, fueling your spirit onward." },
      { location: "Aeroplane", clue: "Soar like wings breaking free from the lion’s den; find freedom above." },
      { location: "Main Building Trees", clue: "Walk beneath towering trees where faithful footsteps carve the path of courage." },
      { location: "Canteen", clue: "Gather nourishment and fellowship as strength for your final challenge." },
      { location: "Bicycle Shed CSE", clue: "Mount your silent steeds for the last ride to victory." }
    ],
    "4": [
      { location: "Agri Lab - 4 Trees Area", clue: "Begin under these mighty trees, finding peace before entering your own lion’s den." },
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Step through gates of healing and divine strength as you prepare to face fear." },
      { location: "Mechanical Trees", clue: "Stand tall among towering steel as you gather courage and resolve." },
      { location: "Library", clue: "Find wisdom here to guide you through darkness and danger with steady faith." },
      { location: "CTC 2 Placement Training", clue: "Ready your mind and courage here where leaders prepare for great challenges." },
      { location: "Cake World Trees", clue: "Sweet-scented shade offers comfort and hope amid trials." },
      { location: "ECE Vending Machine", clue: "Small provisions sustain your journey; find your source here." },
      { location: "Aeroplane", clue: "Wings spread wide above, a symbol of rising beyond fear." },
      { location: "Main Building Trees", clue: "Under these great trees, find strength where courage has always flourished." },
      { location: "Canteen", clue: "Gather renewed strength where fellowship and food bring comfort." },
      { location: "Bicycle Shed CSE", clue: "Prepare your steed for the journey onward." },
      { location: "Emmanuel Auditorium", clue: "End where faith and God’s presence empower final victory over fear." }
    ],
    "5": [
      { location: "Bethesda Gate / Elohim Auditorium", clue: "Start your journey through sacred gates named for healing and strength, stepping boldly into courage." },
      { location: "Mechanical Trees", clue: "Amid the towering steel giants, find strength and resolve to face the lions." },
      { location: "Library", clue: "Seek guidance in stories of faith and triumph amidst great trials." },
      { location: "CTC 2 Placement Training", clue: "Prepare your mind and heart here, ready for the battles of life with courage." },
      { location: "Cake World Trees", clue: "Rest and find peace beneath these fragrant trees, a haven amidst difficulties." },
      { location: "Agri Lab - 4 Trees Area", clue: "Under four mighty trees, steady yourself for the final challenges ahead." },
      { location: "Aeroplane", clue: "Look to giant wings that soar above fear, symbolizing freedom and faith." },
      { location: "Main Building Trees", clue: "Walk beneath towering trees where many have found courage to triumph." },
      { location: "Canteen", clue: "Gather nourishment and strength as fellowship fuels your soul." },
      { location: "Bicycle Shed CSE", clue: "Mount silent steeds, steadfast and ready for your final journey." },
      { location: "Emmanuel Auditorium", clue: "Feel God’s presence surround and empower you in this sacred space." },
      { location: "ECE Vending Machine", clue: "Small offerings here will sustain you to the journey’s close, completing your path of courageous faith." }
    ]
  }
};
